<h2>Novo Produto</h2>
<hr>

	<div class="card card-body mb-3">
		<form enctype="multipart/form-data" name="form" id="form" method="post" action="">
			<legend>Dados do Produto</legend>
			<hr>
			<div class="form-row">
				<div class="form-group col-md-6">
  				<?= $this->form->produto_nome ?>
      	</div>
				<div class="form-group col-md-6">
      		<?= $this->form->produto_imagem ?>
	    	</div>
			</div>
			<div class="form-row">
				<div class="form-group col-md-6">
  				<?= $this->form->marca_id ?>
      	</div>
				<div class="form-group col-md-6">

	    	</div>
			</div>
			<div class="form-row">
				<div class="form-group col-md-6">
      		<?= $this->form->produto_descricao ?>
      	</div>
			</div>
			<div class="form-row">
				<div class="form-group col-md-3">
      		<?= $this->form->produto_valor ?>
      	</div>
				<div class="form-group col-md-3">
      		<?= $this->form->produto_ativo ?>
      	</div>
			</div>
			<button type="submit" class="btn btn-sm btn-primary">Salvar</button>
			<a href="/<?= $this->controllerName?>" class="btn btn-sm btn-danger">Cancelar</a>
		</form>
	</div>
