<h2>Novo Usuário</h2>
<hr>

	<div class="card card-body mb-3">
		<form name="form" id="form" method="post" action="">
			<legend>Dados Pessoais</legend>
			<hr>
			<div class="form-row">
				<div class="form-group col-md-4">
  				<?= $this->form->cargo_id ?>
      	</div>
				<div class="form-group col-md-4">
      		<?= $this->form->loja_id ?>
	    	</div>
				<div class="form-group col-md-4">
	    	</div>

			</div>
			<div class="form-row">
				<div class="form-group col-md-4">
  				<?= $this->form->usuario_nome ?>
      	</div>
				<div class="form-group col-md-4">
      		<?= $this->form->usuario_email ?>
	    	</div>
				<div class="form-group col-md-4">
	    	</div>
			</div>
			<div class="form-row">
				<div class="form-group col-md-4">
  				<?= $this->form->usuario_login ?>
      	</div>
				<div class="form-group col-md-4">
      		<?= $this->form->usuario_senha ?>
	    	</div>
				<div class="form-group col-md-4">
      		<?= $this->form->usuario_ativo ?>
	    	</div>
			</div>
			<button type="submit" class="btn btn-sm btn-primary">Salvar</button>
			<a href="/<?= $this->controllerName?>" class="btn btn-sm btn-danger">Cancelar</a>
		</form>
	</div>
