    <section class="slice bg-base" style="padding:90px 0;">
        <div class="wp-section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="text-center">
                            <h2>Página não encontrada!</h2>
                            <h1 class="font-xl">
                                4<i class="fa fa-times-circle-o"></i>4
                            </h1>
                            <p>
                                A página que você tentou acessar não está disponível neste site.
                                <br>
                                Verifique se você digitou o endereço corretamente e tente novamente.
                            </p>
                            <span class="clearfix"></span>
    
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
    <section class="slice bg-3">
        <div class="text-center p-15">
            <h4>A página procurada não foi encontrada.</h4>
            <p>
                Por favor, verifique se o endereço da página foi digitado corretamente. Você também pode entrar em contato
                com nossa administração através do e-mail contato@sulvistos.com.br.
            </p>
        </div>
    </section>
