<h2>Lojas</h2>
<hr>

<div class="btn-toolbar mb-3" role="toolbar">
	<div class="btn-group mr-2" role="group">
		<div class="input-group-prepend">
			<div class="input-group-text"><span data-feather="search"></span></div>
		</div>

		<button type="button" class="btn btn-secondary" data-toggle="collapse" data-target="#pesquisa" aria-expanded="false" aria-controls="pesquisa">Pesquisar</button>
	</div>

	<a href="/<?= $this->controllerName?>/novo" class="btn btn-success"> Adicionar</a>
</div>

<?php if($this->limpraFiltro): ?><a href="/<?= $this->controllerName?>" class="btn btn-outline-dark">Limpar filtros</a><?php endif;?>

<div class="collapse" id="pesquisa">
	<div class="card card-body">
		<form name="formPesquisa" id="formPesquisa" method="post" action="">
			<div class="form-row">
				<div class="form-group col-md-4">
	            	<?= $this->form->loja_nome ?>
      	</div>
				<div class="form-group col-md-4">
	            	<?= $this->form->estado_id ?>
	    	</div>
				<div class="form-group col-md-4">
	            	<?= $this->form->cidade_id ?>
	    	</div>
			</div>
			<div class="form-row">
				<div class="form-group col-md-4">
	            	<?= $this->form->loja_ativo ?>
      	</div>
			</div>
			<button type="submit" class="btn btn-sm btn-warning">Pesquisar</button>
			<button type="button" class="btn btn-sm btn-danger" data-toggle="collapse" data-target="#pesquisa" aria-expanded="false" aria-controls="pesquisa">Cancelar</button>
		</form>
	</div>
</div>

<table class="table table-hover mt-3">
  <thead class="thead-light">
    <tr>
      <th scope="col">#</th>
      <th scope="col">NOME</th>
      <th scope="col">ESTADO</th>
      <th scope="col">CIDADE</th>
      <th scope="col">CADASTRO</th>
      <th scope="col" class="text-right">
      	<a href="/<?= $this->controllerName?>"><span data-feather="refresh-cw"></span> atualizar dados </th>
    </tr>
  </thead>
  <tbody>
  	<?php
	  	$count = 1;
  		foreach($this->rows as $row) :
  		$row = $this->FormataInputsView($this->cols, $row->toArray());?>

    <tr id="<?=$row['loja_id']?>">
      <th scope="row"><?=$count++?></th>
      <td><?=$row['loja_nome']?></td>
			<td><?=$this->ObjInfo(array('model' => 'Estado','col' => 'estado_nome','id' => $row['fk_estado_id']));?></td>
			<td><?=$this->ObjInfo(array('model' => 'Cidade','col' => 'cidade_nome','id' => $row['fk_cidade_id']));?></td>
			<td><?=$row['loja_cadastro']?></td>
      <td class="text-right">
      	<div class="btn-group">
			  <button type="button" class="btn btn-sm btn-outline-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			    ALTERAR
			  </button>
			  <div class="dropdown-menu">
			    <a class="dropdown-item" href="/<?= $this->controllerName?>/<?=$row['loja_id']?>">Editar</a>
			    <a class="dropdown-item" href="#" onclick="deletar('<?= $this->controllerName?>', <?=$row['loja_id']?>, <?=$row['loja_ativo']?>)">
				    <?php echo $row['loja_ativo'] == 1 ? "Desativar" : "Ativar"?>
				</a>
			  </div>
			</div>
		</td>
    </tr>
	<?php endforeach;?>
  </tbody>
</table>
