<h2>Editar Cliente</h2>
<hr>

	<div class="card card-body mb-3">
		<form name="form" id="form" method="post" action="/<?= $this->controllerName?>/salvar">
			<legend>Dados Pessoais</legend>
			<hr>
			<div class="form-row">
				<div class="form-group col-md-6">
  				<?= $this->form->cliente_nome ?>
      	</div>
				<div class="form-group col-md-6">
      		<?= $this->form->cliente_email ?>
	    	</div>
			</div>
			<div class="form-row">
				<div class="form-group col-md-6">
      		<?= $this->form->cliente_login ?>
      	</div>
				<div class="form-group col-md-6">
      		<?= $this->form->cliente_ativo ?>
      	</div>
			</div>
			<?= $this->form->cliente_id ?>								
			<button type="submit" class="btn btn-sm btn-primary">Salvar</button>
			<a href="/<?= $this->controllerName?>" class="btn btn-sm btn-danger">Cancelar</a>
		</form>
	</div>
