<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="novo" aria-hidden="false">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="novo">Novo cadastro</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <form name="formNovo" id="formNovo" method="post" action="/<?= $this->controllerName?>/salvar">

			<!--TROCAR O NOME DO CAMPO -->
      <input hidden="hidden" id="id" name="id">

      <div class="form-group">
        <?= $this->form->categoria_marketing_id ?>
      </div>
      <div class="form-group">
        <?= $this->form->setor_comercial_id ?>
      </div>
      <div class="form-group">
        <?= $this->form->nome ?>
      </div>
      <div class="form-group">
        <?= $this->form->nome_relatorio ?>
      </div>
      <div class="form-group">
        <?= $this->form->site ?>
      </div>      
		</div>
		<div class="modal-footer">
      <a href="/<?= $this->controllerName?>" class="btn btn-secondary">Voltar</a>
			<button type="submit" class="btn btn-primary">Salvar</button>
		</form>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
    $(window).on('load',function(){
        $('#modal').modal('show');
    });
</script>