
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="index, follow">
    <title>Uniritter - Banco de Dados - Grau A</title>

    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/jasny-bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/login.css">

    <script type="text/javascript" src="/js/jquery.3.2.1.min.js"></script>
</head>
<body class="text-center">
  <?php echo $this->layout()->content?>
</body>
</html>
